#!/bin/bash
# Railway PostgreSQL 配置脚本
# 用法: bash scripts/setup-pg.sh

echo "=============================================="
echo "  Railway PostgreSQL 配置向导"
echo "=============================================="
echo ""
echo "📋 步骤 1: 打开 Railway 控制台"
echo ""
echo "   请打开浏览器访问:"
echo "   👉 https://railway.app/project"
echo ""
echo "   使用你的 GitHub 账号登录"
echo ""
echo "📋 步骤 2: 找到项目"
echo ""
echo "   在项目列表中点击: wlj-production"
echo ""
echo "📋 步骤 3: 添加 PostgreSQL 数据库"
echo ""
echo "   点击页面下方的 "New" 按钮"
echo "   → 选择 "Database""
echo "   → 选择 "Add PostgreSQL""
echo ""
echo "📋 步骤 4: 等待部署"
echo ""
echo "   Railway 会自动:"
echo "   - 创建 PostgreSQL 数据库实例"
echo "   - 将 DATABASE_URL 注入到环境变量"
echo "   - 重新部署你的项目"
echo ""
echo "   这个过程大约需要 2-3 分钟"
echo ""
echo "📋 步骤 5: 验证 PostgreSQL 连接"
echo ""
echo "   部署完成后，运行:"
echo ""
echo "   curl https://wlj-production.up.railway.app/api/health"
echo ""
echo "   如果返回: {\"status\":\"ok\",\"db\":\"postgresql\",...}"
echo "   则 PostgreSQL 配置成功 ✅"
echo ""
echo "📋 步骤 6: 同步数据到 PostgreSQL"
echo ""
echo "   node scripts/sync-to-remote.js"
echo ""
echo "=============================================="
echo ""
echo "⚠️  注意: Railway 的免费版 PostgreSQL"
echo "    包含 500MB 存储空间，完全够用"
echo "=============================================="
