#!/bin/bash
# 线上数据库/接口状态检查（本项目只使用线上 PostgreSQL，不在本地建库）
# 用法: bash scripts/setup-pg.sh

API_BASE="${API_URL:-https://www.weilaijia20210101.com/api}"

echo "=============================================="
echo "  线上 PostgreSQL / 接口状态检查"
echo "=============================================="
echo ""
echo "📡 API 地址: ${API_BASE}"
echo ""
echo "📋 步骤 1: 检查接口与数据库状态"
echo ""
echo "   curl ${API_BASE}/health"
curl -s "${API_BASE}/health" || echo "   ❌ 无法连接"
echo ""
echo "   返回 {\"status\":\"ok\",\"db\":\"postgresql\"} 表示线上数据库正常 ✅"
echo ""
echo "📋 步骤 2: 确认服务器环境变量"
echo ""
echo "   线上服务器需要配置 DATABASE_URL（指向线上 PostgreSQL，不能用 localhost）"
echo "   本地开发写进 .env.local，同样是线上库的连接串"
echo ""
echo "📋 步骤 3: 重启服务"
echo ""
echo "   cd <项目目录> && git pull && npm install && npm run build && npm run start"
echo ""
echo "📋 步骤 4: 确认登录接口与其它接口同源"
echo ""
echo "   curl -X POST ${API_BASE}/auth/login \\"
echo "        -H 'Content-Type: application/json' -d '{\"phone\":\"...\",\"password\":\"...\"}'"
echo ""
echo "=============================================="
